version: 0.2

env:
  parameter-store:
    ECR_REPO_NAME: "/ski-recommender/development/ecrRepoName"
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME
      - GIT_COMMIT_ID=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - echo Building image and running tests
      - make test
      - ECR_IMAGE_NAME=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME:$GIT_COMMIT_ID
      - docker tag kfarbman/ski-recommender:latest $ECR_IMAGE_NAME
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $ECR_IMAGE_NAME
      - printf '[{"name":"ski-recommender-development","imageUri":"%s"}]' $ECR_IMAGE_NAME > imagedefinitions.json

artifacts:
  files: imagedefinitions.json
